export const rsaConst = {
  // Registri
  REG_LIBRO_GIORNALE: 1,
  REG_ACQUISTI: 2,
  REG_FATTURE_EMESSE: 3,
  REG_CORRISPETTIVI: 4,
  REG_FATTURE_SOSP: 5,
  REG_ACQUISTI_CEE: 6,
  REG_FATTURE_EMESSE_CEE: 7,

  // Tipo Iva
  TIPO_IVA_IMPONIBILE: 1,
  TIPO_IVA_ESENTE: 2,
  TIPO_IVA_NON_IMPONIBILE: 3,
  TIPO_IVA_NON_SOGGETTO: 4,
  TIPO_IVA_RIT_ACCONTO: 5,
  TIPO_IVA_NON_IMP_ART8_2: 6,
  TIPO_IVA_RETTIFICA: 7,
  TIPO_IVA_EXP_IMP: 8,
  TIPO_IVA_CREDITI_DIV: 9,
  TIPO_IVA_CORRIS_VENT: 10,
  TIPO_IVA_ESC_ART15: 11,
  TIPO_IVA_REG_MARGINE: 12,
  TIPO_IVA_REVERSE_CHARGE: 13,
  TIPO_IVA_ASSOLTA_ALTRO_STATO_UE: 14,

  // Tipo di Imputazione
  IMP_MANUALE: 1,
  IMP_VAL_ASS_TOT_IMPONIBILE: 2,
  IMP_VAL_ASS_TOT_IVA: 3,
  IMP_VAL_ASS_TOT_REGISTRAZIONE: 4,
  IMP_VAL_ASS_TOT_ARROTONDAMENTI: 5,
  IMP_VAL_ASS_TOT_IVA_DETRAIBILE: 6,
  IMP_VAL_ASS_TOT_IVA_INDETRAIBILE: 7,
  IMP_VAL_ASS_TOT_CAUZIONI_CONSEGNATE: 8,
  IMP_VAL_ASS_TOT_CAUZIONI_RESE: 9,
  IMP_SALDO_CAUZIONI: 10,
  IMP_VAL_ASS_TOT_IMPONIBILE_PIU_IVA_INDETRAIBILE: 11,
  IMP_VAL_ASS_TOT_COMMISSIONI: 12,
  IMP_VAL_ASS_TOT_IMPONIBILE_NEGATIVO: 13,
  IMP_VAL_ASS_TOT_IVA_NEGATIVA: 14,
  IMP_VAL_ASS_TOT_IMPONIBILE_POSITIVO: 15,
  IMP_VAL_ASS_TOT_IVA_POSITIVA: 16,

  DARE: 0,
  AVERE: 1,
  BLANC: 2,

  GEST_IVA_NORMALE: 0,
  GEST_IVA_SOSPESA: 1,
  GEST_IVA_MOVIMENTA: 2,

  CAC_INVISIBILE: 0,
  CAC_FACOLTATIVO: 1,
  CAC_OBBLIGATORIO: 2,

  MAX_CON_ROW: 20,

  // Causali
  REL_CLI: 0,
  REL_FOR: 1,
  REL_NIE: 2,

  // Nazionalità
  NAZ_ITA: 1,
  NAZ_STR: 2
}

export const dimensionConsts = {
  //GRID
  DEFAULTGRID: 20,
  SEARCHGRID: 10,

  //Height
  HEIGHTSEARCHWRAPPER: '370',
  HEIGHTGRIDWRAPPER: '550',

  //Prima Nota
  IVAGRID: 7,
  PNOTARIGHEGRID: 100,
  ANALITICS: 50,
  SCADENZE: 50
}
